{% set package_name = "pyca" %}
{% set import_name = "pyca" %}

package:
  name: {{ package_name }}
  version: "3.3.1"

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  missing_dso_whitelist:
    - '*/libca.*'
    - '*/libCom.*'

requirements:
  build:
    - epicscorelibs
    - python >=3.9
    - pip
    - numpy
    - setuptools
    - setuptools_scm
  host:
    - python >=3.9
    - epicscorelibs
    - numpy
    - pip
    - setuptools
    - setuptools_dso
    - setuptools_scm
  run:
    - python
    - epicscorelibs
    - numpy

test:
  requires:
    - pcaspy
  imports:
    - pyca
    - psp

about:
  home: https://github.com/slaclab/pyca
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: PyCA - lightweight bindings for Python applications to access EPICS PVs.

  description: |
    PyCA (Python Channel Access) is a module that offers lightweight
    bindings for Python applications to access EPICS PVs. It acts as
    a channel access client, much like pyepics. The intention of the 
    module is to provide better performance for embedded applications,
    rather than to provide an interactive interface. The most significant
    gains will be found when monitoring large waveforms that need to be
    processed before exposing them the Python layer.      
  dev_url: https://github.com/slaclab/pyca
