{% set package_name = "pyca" %}
{% set import_name = "pyca" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}
{% set EPICS = '3.14.12.6' %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv



requirements:
  build:
  - python {{ PY_VER }}*
  - epics-base {{ EPICS }}*
  - numpy {{ NPY_VER }}*
  - setuptools_scm
  - pip
  run:
  - python {{ PY_VER }}*
  - epics-base {{ EPICS }}*
  - numpy {{ NPY_VER }}*



test:
  requires:
  - pcaspy
  imports:
  - pyca
  - psp



about:
  home: https://github.com/slaclab/pyca
  licence: SLAC Open Licence
  summary: Python Channel Access
